---
name: Engineering One Pager
about: Create a one page to collect engineering requirements for a project
title: "[OnePager]"
labels: 
assignees: ''

---


**Project Title: (i.e. $ IAP) **

#### Objectives
Support selling IAPs with real $ money

#### Functional Requirements:
1. Inventory service support purchasing IAP items with $
2. Both android and iOS client supports user to purchase IAP items with $

#### Non-functional Requirements:
- Performance:
- Security: 
- Usability:

#### Constraints:
- Timeline: 4 sprints
- Technology limitations: 

#### Scope and Deliverables:
